import { Geist, Geist_Mono } from "next/font/google";
import "./CSS/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "E-tree Power",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html  className={`${geistSans.variable} ${geistMono.variable}`} lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
